apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: postgres-01
  namespace: rucio-guide
spec:
  interval: 5m
  targetNamespace: rucio-guide
  chart:
    spec:
      chart: postgresql
      version: 12.1.11
      sourceRef:
        kind: HelmRepository
        name: bitnami 
        namespace: flux-system
      interval: 1m
  install:
    skipCRDs: false
    remediation:
      retries: 3
  values:
    image:
      registry: docker.io
      repository: bitnami/postgresql
      tag: latest

    persistence:
      enabled: true

    global:
      postgresql:
        auth:
          username: dbuser
          password: hellohello
          database: dbuser
