apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
   name: repos
   namespace: flux-system
spec:
   interval: 10m0s
   sourceRef:
      kind: GitRepository
      name: flux-system
   path: ./repos
   prune: true
