apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: rucio-guide
  namespace: flux-system
spec:
  interval: 5m0s
  dependsOn:
    - name: repos
  sourceRef:
    kind: GitRepository
    name: flux-system
  path: ./apps/rucio-guide/apps
  prune: true
